# autogenerated by txs
#include:txfonts
\OML/mak/b/it#S
\OML/mak/m/it#S
\OT1/txr/b/n#S
\T1/mak/m/n#S
\__file_name=txfonts.sty#S
\__file_seen_txfonts.sty:#S
\__hook package/txfonts/after#S
\__hook package/txfonts/before#S
\__hook txfonts#S
\__hook_next package/txfonts/after#S
\__hook_next package/txfonts/before#S
\g__hook_package/txfonts/after_reversed_tl#S
\g__hook_package/txfonts/before_reversed_tl#S
\symkerkisnumbers#S
\unprocessedoptions-txfonts.sty#S
csnameendcsname#S
txfonts.sty#S
