# autogenerated by txs
\acontracted[opt]{arg1}{arg2}{arg3}{arg4}#S
\acontracted{arg1}{arg2}{arg3}{arg4}#S
\acontraction[opt]{arg1}{arg2}{arg3}{arg4}#S
\acontraction{arg1}{arg2}{arg3}{arg4}#S
\bcontracted[opt]{arg1}{arg2}{arg3}{arg4}#S
\bcontracted{arg1}{arg2}{arg3}{arg4}#S
\bcontraction[opt]{arg1}{arg2}{arg3}{arg4}#S
\bcontraction{arg1}{arg2}{arg3}{arg4}#S
\contraction#S
\filedate#S
\fileversion#S
\nomathglue{arg1}#S
\simplewickcontact#S
\\acontracted#S
\\acontraction#S
\\bcontracted#S
\\bcontraction#S
